### PR TITLE
Assets Add/Plus Icons

### PR DESCRIPTION
**Pull request by jsntv200**
Hey,

Noticed the nicer looking Plus and Minus icons in the Assets Extension and thought I'd pull them across. Also a couple of other small fixes that have been bugging me. Changes are :
- Revised Plus, Minus and Upload icons.
- Firefox fix removing a 1px gap under the page part tabs, adding line-height fixes it.
- Lined up the Status column elements.
- Added a disabled button to the Page index view.

These changes are also in the icons branch of my Radiant fork if you like the changes and want to pull it straight in.

### CODE REVIEW

**Comment by jlong** [comment]
@jsntv200, thanks for working on this. I'm afraid I'd like to stick with the icons we have. Part of it is I'm not sure about the rights on the icons here (I think they are from the Silk icon set). But the other part is that I like the flatter look for Radiant. I'd love to pull in your Firefox fix though if you'd remove the other commits from this pull request?

**Comment by jsntv200** [comment]
No problem. Might be a good idea for Assets to use the same flat icons for consistency if its a core extension. Do you want to keep the status column alignment tweak, it's pretty minor. Just adds the same padding as for Published as the Draft and Hidden. Still fairly new to this, what's the best method to remove the other commits and re-submit ? Are changes to the branch automatically picked up or do I have to submit a new pull request ?

**Comment by jlong** [comment]
Yeah I agree. The assets extension should use the same icons for consistency. I think that these icons were just hanging around from a previous version of the extension, but I'll be taking a cleanup pass on the assets extension before we release 1.0. I'll make sure it's consistent by then.

On the alignment tweak, which commit are you talking about?

**Comment by jlong** [comment]
Oh, and I'm not quite sure about adjusting pull requests. I've never done it myself either.

**Comment by jlong** [comment]
Ah, this guide looks like it could be helpful:
http://help.github.com/pull-requests/

**Comment by jsntv200** [comment]
The alignment tweak fell into the "Added upload icon, adjusted position of the icons" commit. Basically just adding 6px left/right padding to the .published_status & .reviewed_status classes and indenting the Status heading. Makes the Published / Reviewed text look centred above a Draft or Hidden badge.

I'll see what happens pushing changes to this branch, otherwise i'll just make a new branch / pull request.

**Comment by jlong** [comment]
Ah, OK. I see what you mean about the status alignment issue. I'm not sure though. When I worked on this before I think I liked the hard left alignment instead of trying to align the text inside the status badge with the text outside. The reason is that the dark background on the badge seems to give it enough visual weight that aligning to it's left edge works well. But I'm guessing that it looks funny to you?

The trouble with this kind of alignment issue is that there isn't really a right answer. Some people like it one way, others like it another.

**Comment by jsntv200** [comment]
True.. to my eye it looks a little whack but I can just use overrides if need be. Will close this and just open an new request for the firefox fix.

**Pull request closed without merging**
